### ISSUE TITLE
how to solve

### ISSUE THREAD

**Issue by tl123987** [soblin/matplotlibcpp17#33]
![图片](https://github.com/soblin/matplotlibcpp17/assets/65206700/8f651b67-d653-4043-92d2-b96aa45f47b8)

**Comment by tl123987** [comment]
make no hapen

**Comment by soblin** [comment]
This is a header only library so there is nothing to make/build.
You just "make install"

**Comment by tl123987** [comment]
Okay, I originally thought I needed to rely on libraries

**Comment by tl123987** [comment]
matplotlibcpp17::matplotlibcpp17   this may have confuse
