### ISSUE TITLE
bug with clang12

### ISSUE THREAD

**Issue by QiuYue-bit** [soblin/matplotlibcpp17#35]
when i use gcc-9,it's ok,but when i change to clang , there is a error occured:
/usr/include/pybind11/pybind11.h:1008:9: error: no matching function for call to 'operator delete'
        ::operator delete(p, s, std::align_val_t(a));

is anyone know how can i fix this problem?

**Comment by soblin** [comment]
- https://github.com/pybind/pybind11/issues/1604#issuecomment-459796241
- https://github.com/pybind/pybind11/issues/1604#issuecomment-44338578

It looks like you need to pass "-fsized-deallocation" option for use with Clang.
